### ISSUE TITLE
Outputting to XML Needs End Tag

### ISSUE THREAD

**Issue by Asbjoedt** [RvanVeenendaal/Spreadsheet-Complexity-Analyser#19]
Hello Remco

Outputting the SCA results to XML is such a neat feature.
However, we discovered (a long time ago, but forgot to report) that the last line of the XML syntax is missing the end tag.

`</spreadsheetComplexityResults>`

Therefore, we manually insert it after each output.

**Comment by RvanVeenendaal** [comment]
Solved in new version.
